CREATE OR REPLACE PROCEDURE salary_std_dev(OUT SALARYSTDDEV DOUBLE)
    LANGUAGE SQL
    BEGIN
        DECLARE avg_salary DOUBLE;
        DECLARE n DOUBLE;

        SET avg_salary = (SELECT AVG(SALARY) FROM DB2INST1.EMPLOYEE);
        SET n = (SELECT COUNT(SALARY) FROM DB2INST1.EMPLOYEE);

        SET SALARYSTDDEV = (SELECT POWER(SUM(POWER(SALARY - avg_salary, 2)) / n, 0.5) FROM DB2INST1.EMPLOYEE LIMIT 1);
    END@