select F.FACILITYID,
       F.FACILITYNAME,
       F.GEOLOCATION,
       DECIMAL(DB2GSE.ST_Distance(F.GEOLOCATION, DB2GSE.ST_Point(-72.993983, 40.824369, 1), 'STATUTE MILE'), 8,
               2) as DISTANCE_STATUTE_MILE
from CSE532.FACILITY F
         inner join CSE532.FACILITYCERTIFICATION FC on F.FACILITYID = FC.FACILITYID
where FC.ATTRIBUTEVALUE = 'Emergency Department'
  and DB2GSE.ST_Intersects(F.GEOLOCATION,
                           DB2GSE.ST_Buffer(DB2GSE.ST_Point(-72.993983, 40.824369, 1), 10.0, 'STATUTE MILE')) = 1
order by DISTANCE_STATUTE_MILE
limit 1;
